class_name Car extends RigidBody3D



signal debug_lamp_changed



enum TransmissionType {FULLY_MANUAL, AUTOMATIC, CONTINUOUSLY_VARIABLE, SEMI_AUTO}



@export_group("Profiles")
@export var fuel: Fuel

@export_subgroup("Gearbox")
@export var shift_assist: ShiftAssistProfile
@export var auto_gearbox: AutoGearboxProfile
@export var cvt: CVTProfile

@export_subgroup("Stability")
## Anti-lock Braking System.
@warning_ignore("shadowed_global_identifier")
@export var abs: ABSProfile
## Electronic Stability Program.
@export var esp: ESPProfile
## Brake-based Traction Control System.
@export var btcs: BTCSProfile
## Throttle-based Traction Control System
@export var ttcs: TTCSProfile

@export_group("Other")
@export var Debug_Mode := false
@export var LooseSteering := false #simulate rack and pinion steering physics (EXPERIMENTAL) # May belong in ControlsConfig, unsure.
# meta
@export var Controlled := true

@export_group("Chassis")
@export_custom(PROPERTY_HINT_NONE, "suffix:kg") var Weight := 900.0

@export_group("Body")
@export var LiftAngle := 0.1
@export var DragCoefficient := 0.25
@export var Downforce := 0.0

@export_group("Steering")
@export var AckermannPoint := -3.8
@export var Steer_Radius := 13.0

@export_group("Drivetrain")
@export var Powered_Wheels: Array[String] = ["fl","fr"]

## Ratio multiplier of the gearbox.
@export var final_drive := 4.250
## Ratios of forward gears.
@export var GearRatios: Array[float] = [ 3.250, 1.894, 1.259, 0.937, 0.771 ]
## Ratio of reverse gear.
@export var reverse_ratio := 3.153
## Ratio multiplier of the drivetrain.
@export var ratio_multi := 9.5 # Useless, basically final_drive_2
@export var StressFactor := 1.0
@export var GearGap := 60.0
@export var DSWeight := 150.0 # Leave this be, unless you know what you're doing.

@export var transmission_type := TransmissionType.FULLY_MANUAL

@export_group("Differentials")
@export var Locking := 0.1
@export var CoastLocking := 0.0
@export var Preload := 0.0
@export var Centre_Locking := 0.5
@export var Centre_CoastLocking := 0.5
@export var Centre_Preload := 0.0

@export_group("Engine")
## Flywheel lightness.
@export var RevSpeed := 2.0
@export var EngineFriction := 18000.0
@export var EngineDrag := 0.006
@export var ThrottleResponse := 0.5
@export var DeadRPM := 200.0

@export_group("ECU")
@export var RPMLimit := 7000.0
@export var LimiterDelay := 4
@export var IdleRPM := 800.0
@export var ThrottleLimit := 0.0
@export var ThrottleIdle := 0.25
@export var VVTRPM := 4500.0 # set this beyond the rev range to disable it, set it to 0 to use this vvt state permanently

@export_group("Torque normal state")
@export var BuildUpTorque := 0.0035
@export var TorqueRise := 30.0
@export var RiseRPM := 1000.0
@export var OffsetTorque := 110.0
@export var FloatRate := 0.1
@export var DeclineRate := 1.5
@export var DeclineRPM := 3500.0
@export var DeclineSharpness := 1.0

@export_group("Torque variable valve timing")
@export var VVT_BuildUpTorque := 0.0
@export var VVT_TorqueRise := 60.0
@export var VVT_RiseRPM := 1000.0
@export var VVT_OffsetTorque := 70.0
@export var VVT_FloatRate := 0.1
@export var VVT_DeclineRate := 2.0
@export var VVT_DeclineRPM := 5000.0
@export var VVT_DeclineSharpness := 1.0

@export_group("Clutch")
@export var ClutchStable := 0.5
@export var GearRatioRatioThreshold := 200.0
@export var ThresholdStable := 0.01
@export var ClutchGrip := 176.125
@export var ClutchFloatReduction := 27.0
@export var ClutchWobble := 2.5*0
@export var ClutchElasticity := 0.2*0
@export var WobbleRate := 0.0

@export_group("Forced inductions")
@export var MaxPSI := 9.0 # Maximum air generated by any forced inductions
@export var EngineCompressionRatio := 8.0 # Piston travel distance
@export_subgroup("Turbo")
@export_custom(PROPERTY_HINT_GROUP_ENABLE, "Turbo") var TurboEnabled := false
@export var TurboAmount := 1 # Turbo power multiplication.
@export var TurboSize := 8.0 # Higher = More turbo lag
@export var Compressor := 0.3 # Higher = Allows more spooling on low RPM
@export var SpoolThreshold := 0.1 # Range: 0 - 0.9999
@export var BlowoffRate := 0.14
@export var TurboEfficiency := 0.075 # Range: 0 - 1
@export var TurboVacuum := 1.0 # Performance deficiency upon turbo idle
@export_subgroup("Supercharger")
@export_custom(PROPERTY_HINT_GROUP_ENABLE, "Supercharger") var SuperchargerEnabled := false
@export var SCRPMInfluence := 1.0
@export var BlowRate := 35.0
@export var SCThreshold := 6.0

## Current RPM.
var rpm := 0.0
var rpmspeed := 0.0
var resistancerpm := 0.0
var resistancedv := 0.0
## Current transmission gear.
var gear := 0
var limiter_delay := 0
var actualgear := 0
var gearstress := 0.0
## Actual engine throttle.
var throttle := 0.0:
	set(value): throttle = clamp(value, 0.0, 1.0)
var cvtaccel := 0.0
var shift_assist_delay := 0
## Shift assist step.
var sassiststep := 0
var clutchin := false
var gasrestricted := false
var revmatch := false
## Throttle input.
var gaspedal := 0.0:
	set(value): gaspedal = clamp(value, 0.0, ConfigManager.data.controls.max_throttle)
var brakepedal := 0.0:
	set(value): brakepedal = clamp(value, 0.0, ConfigManager.data.controls.max_brake)
var clutchpedal := 0.0:
	set(value): clutchpedal = clamp(value, 0.0, 1.0)
var clutchpedalreal := 0.0:
	set(value): clutchpedalreal = clamp(value, 0.0, ConfigManager.data.controls.max_clutch)
## Final steering target after assists and decay.
var final_steer := 0.0:
	set(value): final_steer = clamp(value, -1.0, 1.0)
## Raw steering target from key/mouse/accel input.
var steer_target := 0.0:
	set(value): steer_target = clamp(value, -1.0, 1.0)
var abs_delay := 0.0
var tcsweight := 0.0
var tcsflash := false
var espflash := false
var tcs_flash_timer: float = 0.0
## Current gear ratio (gear * final_drive).
var ratio := 0.0
var brake_allowed := 1.0
## Real engine torque.
var engine_torque := 0.0
## Does the engine inject and ignite fuel?
var is_ignition_on := true
## The amount of vaccuum.
var stall_resistance := 0.0

## Final brake pressure.
var brakeline := 0.0
var handbrakepull := 0.0:
	set(value): handbrakepull = clamp(value, 0.0, ConfigManager.data.controls.max_handbrake)
var dsweight := 0.0
var dsweightrun := 0.0
var diffspeed := 0.0
var diffspeedun := 0.0
var locked := 0.0
var c_locked := 0.0
var wv_difference := 0.0
var rpmforce := 0.0
var whinepitch := 0.0
var turbopsi := 0.0
var scrpm := 0.0
var boosting := 0.0
var rpmcs := 0.0
var rpmcsm := 0.0
var currentstable := 0.0
var steering_geometry := [0.0, 0.0]
var resistance := 0.0
var wob := 0.0
var ds_weight := 0.0
var steer_torque := 0.0
var steer_velocity := 0.0
var drivewheels_size := 1.0

var steering_angles := []
var max_steering_angle := 0.0
var assistance_factor := 0.0



var pastvelocity := Vector3(0, 0, 0)
var gforce := Vector3(0, 0, 0)
var clock_mult := 1.0
var dist := 0.0
var stress := 0.0

# control flags
## Input shift up.
var input_upshift := false
## Input shift down.
var input_downshift := false
var gas := false
var brake := false
var handbrake := false
var clutch := false
## Powered wheel nodes.
var c_pws := []

var velocity := Vector3(0, 0, 0)
var rvelocity := Vector3(0, 0, 0)

# draw debug
var front_wheels := []
var rear_wheels := []
var front_load := 0.0
var total := 0.0
var weight_dist := [0.0, 0.0]

var debug_lamp := false:
	set(value): debug_lamp = value; debug_lamp_changed.emit()

## The current amount of fuel in [code]liters[/code].
@onready var current_fuel := fuel.max_fuel



#region internal
func _input(event: InputEvent) -> void:
	if event.is_action_pressed("toggle_debug_mode"):
		Debug_Mode = !Debug_Mode
	if event.is_action_pressed("ignition"):
		if is_ignition_on: stop_engine()
		else: start_engine()


func _ready():
	#bullet_fix()
	# Multi-car: register with the manager (if the autoload is configured) so
	# the active car can be tracked and cycled. Resolved by-name to avoid a
	# compile dependency on the autoload.
	var car_manager := _find_car_manager()
	if car_manager != null:
		car_manager.call("register", self)
	# Auto-start the engine for spark engines (you turn the key) and for
	# diesels that are already cranking above their auto-ignition threshold.
	# The fuel resource may be null in tests; default to spark behavior.
	var should_start := true
	if fuel != null and "ignition_type" in fuel:
		# COMPRESSION = 1 in the IgnitionType enum on Fuel. Compare by value
		# rather than the symbol so older Fuel resources (without the field)
		# don't blow up.
		if fuel.ignition_type == 1:  # IgnitionType.COMPRESSION
			should_start = fuel.should_compression_autostart(rpm)
	if should_start:
		start_engine()
	for i in Powered_Wheels:
		var wh := get_node(i)
		c_pws.append(wh)


func _find_car_manager() -> Node:
	# CarManager is set up as an autoload (Project Settings → Autoload).
	# Resolved by-name so this script still loads if the autoload isn't wired.
	if get_tree() == null:
		return null
	var root := get_tree().root
	if root.has_node("CarManager"):
		return root.get_node("CarManager")
	return null


func _process(_delta):
	if Debug_Mode: draw_debug()


func _physics_process(delta):
	if len(steering_angles) > 0:
		max_steering_angle = 0.0
		for i in steering_angles:
			max_steering_angle = maxf(max_steering_angle, i)
			
		assistance_factor = 90.0 / max_steering_angle
	steering_angles = []
	
	velocity = global_transform.basis.orthonormalized().transposed() * (linear_velocity)
	rvelocity = global_transform.basis.orthonormalized().transposed() * (angular_velocity)
	
	mass = Weight / 10.0 # Shouldn't this be the gravity?
	aero()
	
	gforce = (linear_velocity - pastvelocity) * ((Constants.UNIT_TO_METER / Physics.EARTH_GRAVITY) / delta)
	pastvelocity = linear_velocity
	
	gforce = global_transform.basis.orthonormalized().transposed() * gforce
	
	controls()
	
	ratio = 10.0
	
	shift_assist_delay -= 1
	
	transmission()
	
	var steeroutput := final_steer
	
	## Reduces steering sensitivity as you approach max angle.
	var steer_reduction := pow(max_steering_angle / 90.0, 2) * 0.5
	steeroutput *= abs(final_steer) * (steer_reduction) + (1.0 - steer_reduction)
	
	if abs(steeroutput) > 0.0:
		steering_geometry = [-Steer_Radius / steeroutput, AckermannPoint]
	
	
	if abs: apply_abs(delta)
	if btcs: apply_btcs(delta)
	if ttcs: apply_ttcs(delta)
	if esp: apply_esp()
	
	brakeline = brakepedal * brake_allowed
	
	brakeline = max(brakeline, 0.0)
	
	
	if !is_redline_limiter_on():
		throttle -= (throttle - (gaspedal / (tcsweight * clutchpedal + 1.0) ) ) * (ThrottleResponse / clock_mult)
	else:
		throttle -= throttle * (ThrottleResponse / clock_mult)
	
	apply_redline_limiter()
	apply_idle_throttle_compensation()
	simulate_turbo()
	#var stab := 300.0 # What is this? Remove it? Stab for stability? Some sort of stability strength level?
	simulate_engine()
	drivetrain()
	simulate_fuel()
#endregion internal


func toggle_ignition():
	if is_ignition_on:
		stop_engine()
	else:
		start_engine()


## Is variable valve timing activated?
func is_vvt_active():
	return rpm > VVTRPM


func is_redline_limiter_on():
	return limiter_delay > 0


func is_in_gear():
	return actualgear != 0


func is_throttle_open():
	return throttle > 0.0


func apply_redline_limiter():
	if rpm > RPMLimit and throttle > ThrottleLimit:
		throttle = ThrottleLimit
		limiter_delay = LimiterDelay
	
	limiter_delay -= 1


func apply_idle_throttle_compensation():
	if rpm < IdleRPM:
		throttle = clamp(throttle, ThrottleIdle + ( (IdleRPM - rpm) / IdleRPM), 1.0)
		# The farther from idle, the higher the throttle.
		# TODO: Swap this out for a curve resource.


func simulate_turbo():
	var thr := 0.0
	
	if TurboEnabled:
		thr = (throttle - SpoolThreshold) / (1 - SpoolThreshold)
			
		if boosting > thr:
			boosting = thr
		else:
			boosting -= (boosting - thr) * TurboEfficiency
		
		turbopsi += (boosting * rpm) / ( (TurboSize / Compressor) * 60.9)
		
		turbopsi -= turbopsi * BlowoffRate
		turbopsi = clamp(turbopsi, -TurboVacuum, MaxPSI)
	elif SuperchargerEnabled:
		scrpm = rpm * SCRPMInfluence
		turbopsi = (scrpm / 10000.0) * BlowRate - SCThreshold
		turbopsi = clamp(turbopsi, 0.0, MaxPSI)
	else:
		turbopsi = 0.0


func simulate_engine():
	var torque := 0.0
	
	# Diesel: if the engine is off but the wheels are turning the crank fast
	# enough (clutch engaged in gear, push-start, etc.), it self-ignites.
	if !is_ignition_on and fuel != null and "ignition_type" in fuel:
		if fuel.ignition_type == 1 and fuel.should_compression_autostart(rpm):
			if current_fuel > 0.0:
				start_engine()
	
	if !is_ignition_on:
		throttle = 0.0
		turbopsi = 0.0
	elif is_vvt_active():
		var f := rpm - VVT_RiseRPM
		f = max(f, 0.0)
		torque = (rpm * VVT_BuildUpTorque + VVT_OffsetTorque + pow(f, 2) * (VVT_TorqueRise * Constants.RISE_FACTOR)) * throttle
		torque += ( (turbopsi * TurboAmount) * (EngineCompressionRatio * 0.609) )
		var j := rpm - VVT_DeclineRPM
		j = max(j, 0.0)
		torque /= (j * (j * VVT_DeclineSharpness + (1.0 - VVT_DeclineSharpness) ) ) * (VVT_DeclineRate * Constants.RISE_FACTOR) + 1.0
		torque /= pow(abs(rpm), 2) * (VVT_FloatRate * Constants.RISE_FACTOR) + 1.0
	else:
		var f := rpm - RiseRPM
		f = max(f, 0.0)
		torque = (rpm * BuildUpTorque + OffsetTorque + pow(f, 2) * (TorqueRise * Constants.RISE_FACTOR)) * throttle
		torque += ( (turbopsi * TurboAmount) * (EngineCompressionRatio * 0.609) )
		var j := rpm - DeclineRPM
		j = max(j, 0.0)
		torque /= (j * (j * DeclineSharpness + (1.0 - DeclineSharpness) ) ) * (DeclineRate * Constants.RISE_FACTOR) + 1.0
		torque /= pow(abs(rpm), 2) * (FloatRate * Constants.RISE_FACTOR) + 1.0
	
	rpmforce = (rpm / (pow(abs(rpm), 2) / (EngineFriction / clock_mult) + 1.0)) * 1.0
	if rpm < DeadRPM:
		stop_engine()
		torque = 0.0
		rpmforce /= 5.0
		stall_resistance = 1.0 - rpm / DeadRPM
	else:
		stall_resistance = 0.0
	
	rpmforce += (rpm * (EngineDrag / clock_mult) ) * 1.0
	rpmforce -= (torque / clock_mult) * 1.0
	rpm -= rpmforce * RevSpeed
	
	engine_torque = torque


## Anti-lock braking system entry point. Dispatches to either the legacy
## global pump-duration logic or the advanced per-wheel slip-target
## controller depending on [member ABSProfile.use_advanced_controller].
func apply_abs(delta: float) -> void:
	if abs == null:
		return
	if abs.use_advanced_controller:
		_apply_abs_advanced(delta)
	else:
		_apply_abs_legacy()


## Legacy controller — kept for backward compatibility with vehicles tuned
## against the original behaviour. The wheel's [code]_physics_process[/code]
## sets [member abs_delay] when its longitudinal velocity-deviation crosses
## [member ABSProfile.slip_threshold]; this function just ramps the global
## [member brake_allowed] down while the delay is active and back up when
## it expires. All wheels share a single modulation envelope.
func _apply_abs_legacy() -> void:
	if abs_delay > 0:
		brake_allowed -= abs.pump_rate
	else:
		brake_allowed += abs.pump_rate
	brake_allowed = clamp(brake_allowed, 0.0, 1.0)
	
	abs_delay -= 1
	# Per-wheel modulation isn't used in legacy mode — wheels keep
	# abs_modulation = 1.0 (their default) and the global brake_allowed in
	# car.brakeline does all the work.


## Advanced controller — a per-wheel slip-target ABS modelled on the
## x-engineer.org Xcos reference. For each wheel flagged [code]ContactABS[/code]:
## [br]   1. Compute the longitudinal slip ratio [code]s = 1 − (ω·r)/v[/code].
## [br]   2. Form the slip error [code]e = target_slip − s[/code] and take its sign
##         (bang-bang valve command, ±1).
## [br]   3. Pass that command through a first-order hydraulic lag (time
##         constant T = [member ABSProfile.hydraulic_time_constant]) to get a
##         smooth valve state.
## [br]   4. Integrate [code]K · valve_state[/code] (gain = [member ABSProfile.controller_gain])
##         into the wheel's [member Wheel.abs_modulation], clamped to [0, 1].
## [br][br]
## When the wheel is below [member ABSProfile.min_speed] or the driver isn't
## braking, modulation is relaxed back to 1.0 at [member ABSProfile.release_rate]
## so the next braking event starts from a clean state.
## [br][br]
## The legacy globals ([member brake_allowed], [member abs_delay]) are kept
## consistent so the dash light and any other code reading them still works:
## [member brake_allowed] is set to 1.0 (advanced mode does its work
## per-wheel — see [member Wheel.abs_modulation]) and [member abs_delay] is
## bumped while any wheel is actively cycling.
func _apply_abs_advanced(delta: float) -> void:
	# In advanced mode the global modulator is unity — per-wheel modulation
	# does the actual brake-pressure shaping, so brake_allowed must NOT also
	# scale the brake or we'd double-modulate the wheel being released.
	brake_allowed = 1.0
	
	var any_active := false
	
	# Iterate every wheel, not just driven ones — ABS protects all corners.
	for child in get_children():
		if not "TyreSettings" in child:
			continue
		
		# Wheels with ContactABS = false are unprotected. Snap them open.
		if not child.ContactABS:
			child.abs_modulation = 1.0
			child.abs_active = false
			child.abs_slip_ratio = 0.0
			continue
		
		# Need ground contact for the slip ratio to mean anything.
		if not child.is_colliding():
			child.abs_modulation = move_toward(child.abs_modulation, 1.0, abs.release_rate * delta)
			child.abs_valve_state = move_toward(child.abs_valve_state, 0.0, delta / maxf(abs.hydraulic_time_constant, 0.001))
			child.abs_active = false
			child.abs_slip_ratio = 0.0
			continue
		
		# Longitudinal velocity at the contact patch (in the wheel's local
		# frame, so positive = forward). Used both for the cutoff check and
		# the slip ratio denominator.
		var v_long: float = absf(child.velocity2.z)
		
		# Below cutoff speed, or the driver isn't asking for any meaningful
		# brake → no intervention. Relax modulation back to fully open.
		if v_long < abs.min_speed or brakepedal < 0.05:
			child.abs_modulation = move_toward(child.abs_modulation, 1.0, abs.release_rate * delta)
			child.abs_valve_state = move_toward(child.abs_valve_state, 0.0, delta / maxf(abs.hydraulic_time_constant, 0.001))
			child.abs_active = false
			# Still publish the slip for telemetry, but it's noisy at low v.
			var w_speed_lo: float = absf(child.wv * child.w_size)
			child.abs_slip_ratio = clampf(1.0 - w_speed_lo / maxf(v_long, 0.001), 0.0, 1.0)
			continue
		
		# --- Slip ratio (article eq. 10–11) -----------------------------
		# wv*w_size and velocity2.z are the same units in this codebase
		# (BTCS uses the same comparison). Sign-agnostic via abs() so the
		# formula works for forward and reverse braking alike.
		var wheel_speed: float = absf(child.wv * child.w_size)
		var slip: float = clampf(1.0 - wheel_speed / v_long, 0.0, 1.0)
		child.abs_slip_ratio = slip
		
		# --- Bang-bang command on the slip error ------------------------
		# error > 0 → slip below target → open valve, build pressure (+1)
		# error < 0 → slip above target → close valve, release pressure (-1)
		var error: float = abs.target_slip - slip
		var cmd: float = signf(error)
		
		# Lateral-slip override: if the wheel is sliding sideways hard, the
		# tyre is saturated and any extra brake will just spin the car.
		# Force a release regardless of the longitudinal error.
		var v_lat: float = absf(child.velocity2.x)
		if v_lat > abs.lateral_speed_threshold:
			cmd = -1.0
		
		# --- First-order hydraulic lag ---------------------------------
		# valve_state tracks cmd with time constant T:
		#   T · d(valve)/dt + valve = cmd     →     valve += (cmd-valve)*dt/T
		var alpha: float = clampf(delta / maxf(abs.hydraulic_time_constant, 0.001), 0.0, 1.0)
		child.abs_valve_state += (cmd - child.abs_valve_state) * alpha
		
		# --- Integrate into modulation ---------------------------------
		# K · valve_state is the commanded modulation rate (1/s). Integrate
		# and clamp to [0, 1]. K=12 gives ≈12 modulation-units/sec when the
		# valve is fully committed, so a full 1.0→0.0 release takes ~83 ms.
		child.abs_modulation += child.abs_valve_state * abs.controller_gain * delta
		child.abs_modulation = clampf(child.abs_modulation, 0.0, 1.0)
		
		# Active = noticeably below 1.0 (driver pedal is being modulated).
		# 0.95 hysteresis avoids flicker when the controller idles near full.
		if child.abs_modulation < 0.95:
			child.abs_active = true
			any_active = true
		else:
			child.abs_active = false
	
	# --- Legacy compatibility shims ------------------------------------
	# Some external code (debug.gd dash light) checks abs_delay > 0. Bump
	# it for one tick whenever any wheel is cycling so the indicator stays
	# lit. Fade naturally otherwise.
	if any_active:
		abs_delay = maxf(abs_delay, 1.0)
	abs_delay = maxf(abs_delay - 1.0, 0.0)
	
	# Note: brake_allowed stays at 1.0 here. Per-wheel abs_modulation in
	# wheel.gd does all the actual brake shaping in advanced mode, and
	# stacking both would double-modulate the wheel that's being released.
	# Tools/debug code that read brake_allowed should now read
	# wheel.abs_modulation (per-wheel) or any_active (per-car) instead.


## Brake-based traction control. For each driven wheel that flags
## [code]ContactBTCS[/code], measures forward wheel-spin against ground speed
## and applies a per-wheel brake pulse to kill the spin. Acts like a brake-
## locking diff: braking the spinning wheel forces torque across the diff to
## the gripping one. Only meaningful while the engine is putting torque down
## (throttle open, in gear, clutch engaged).
func apply_btcs(delta: float): # Added delta for consistent timer countdown
	if btcs == null:
		return
	
	# Don't fight the driver while braking — let ABS handle that range.
	if brakepedal > 0.05:
		tcs_flash_timer = 0.0
		tcsflash = false
		return
	
	# Need the engine actually trying to drive the wheels.
	if not is_in_gear() or clutchpedal < 0.1 or throttle <= 0.0:
		tcs_flash_timer = 0.0
		tcsflash = false
		return
	
	var any_intervention := false
	
	for w in c_pws:
		if not w.ContactBTCS:
			continue
		if not w.is_colliding():
			continue
		
		# Forward speed under the wheel (m-ish/s in this codebase's units).
		var ground_speed: float = absf(w.velocity2.z)
		# Wheel rim speed at the contact patch.
		var wheel_speed: float = absf(w.wv * w.w_size)
		
		# Slip ratio: how much the wheel is over-spinning the ground beneath
		# it. Use a small floor on the denominator so a stationary launch
		# doesn't divide by ~0 (we want it to trip during a burnout).
		var slip_excess: float = wheel_speed - ground_speed
		var threshold: float = btcs.slip_threshold
		
		if slip_excess > threshold:
			# Scale brake pressure with how far past the threshold we are.
			# btcs.sensitivity governs the slope.
			var over: float = slip_excess - threshold
			var brake_amount: float = over * btcs.sensitivity
			brake_amount = clampf(brake_amount, 0.0, 1.0)
			w.tc_brake = maxf(w.tc_brake, brake_amount)
			any_intervention = true
	
	# PERSISTENCE FIX: Keep the flash on for at least 0.2 seconds.
	if any_intervention:
		tcs_flash_timer = 0.2
		tcsflash = true
	else:
		tcs_flash_timer = maxf(0.0, tcs_flash_timer - delta)
		tcsflash = tcs_flash_timer > 0.0


## Throttle-based traction control. Inspects the same set of wheels (those
## flagged [code]ContactTTCS[/code]) and feeds [member tcsweight], which the
## existing throttle pipeline already uses to scale gas pedal -> throttle
## (see _physics_process). Higher tcsweight = more throttle reduction.
func apply_ttcs(delta: float): # Added delta for smooth decay
	if ttcs == null:
		return
	
	if not is_in_gear() or clutchpedal < 0.1:
		# tcsweight is reset each frame by drivetrain(); nothing to do.
		return
	
	var target_weight := 0.0
	
	for w in c_pws:
		if not w.ContactTTCS:
			continue
		if not w.is_colliding():
			continue
		
		var ground_speed: float = absf(w.velocity2.z)
		var wheel_speed: float = absf(w.wv * w.w_size)
		var slip_excess: float = wheel_speed - ground_speed
		
		if slip_excess > ttcs.slip_threshold:
			var over: float = slip_excess - ttcs.slip_threshold
			target_weight += over * ttcs.sensitivity
	
	# SMOOTHING FIX: Instant response when engaging, but decays smoothly.
	# This stops the wild on/off oscillations.
	if target_weight > tcsweight:
		tcsweight = target_weight # Instant cut to save traction
	else:
		# Gradually ease off the throttle cut (decay rate of ~5.0 can be adjusted)
		tcsweight = move_toward(tcsweight, target_weight, 5.0 * delta)
	
	# Visual flash persistence tied to TTCS intervention as well
	if tcsweight > 0.01:
		tcs_flash_timer = 0.2
		tcsflash = true

## Electronic stability program. Compares actual yaw rate to the yaw rate
## the driver is asking for (steering input). Brakes a single wheel to
## rotate the car back onto the requested arc:
##   * Oversteer (car rotating more than requested): brake the OUTER FRONT
##     wheel — pushes the nose outward, scrubs off rotation.
##   * Understeer (car rotating less than requested): brake the INNER REAR
##     wheel — pivots the rear, helps the car turn in.
##
## Wheels opt in via [member wheel.ESP_Role] set to one of
## "front_left", "front_right", "rear_left", "rear_right".
func apply_esp():
	if esp == null:
		return
	
	# ESP needs forward speed to be meaningful; below walking pace, skip.
	var forward_speed: float = velocity.z
	if absf(forward_speed) < 2.0:
		espflash = false
		return
	
	# Yaw rate the chassis is actually doing, in rad/s. rvelocity is the
	# car's angular velocity in local space; .y is yaw.
	var actual_yaw: float = rvelocity.y
	
	# Driver-requested yaw rate: a bicycle-model estimate using the car's
	# steering radius. final_steer is normalized [-1,1]; full lock at unit
	# input maps to a turn radius of Steer_Radius.
	var desired_yaw := 0.0
	if absf(final_steer) > 0.001 and Steer_Radius > 0.0:
		var turn_radius: float = Steer_Radius / absf(final_steer)
		desired_yaw = (forward_speed / turn_radius) * signf(final_steer)
	
	var yaw_error: float = actual_yaw - desired_yaw
	
	# Convention: positive yaw = turning one way, negative = the other.
	# Whether that's "left" or "right" depends on Godot/your scene's basis,
	# but the *relationship* is consistent — so we use the sign of
	# final_steer to figure out which side is inner vs outer.
	var steer_sign: float = signf(final_steer) if absf(final_steer) > 0.001 else signf(actual_yaw)
	if steer_sign == 0.0:
		espflash = false
		return
	
	# Oversteer if the car is rotating MORE than requested in the same
	# direction as the steering. Understeer is the inverse.
	# yaw_error has the same sign as steer_sign => oversteer (overshooting).
	# yaw_error has opposite sign to steer_sign => understeer (undershooting).
	var oversteer_amount: float = yaw_error * steer_sign  # +ve = oversteer
	
	var intervened := false
	
	if oversteer_amount > esp.yaw_threshold:
		# Brake the OUTER FRONT.
		# steer_sign > 0 means turning one way; "outer" is the opposite side.
		# We can't know absolute left/right without the car's basis, but we
		# can pick the wheel whose local x has the OPPOSITE sign of steer_sign.
		var brake_amount: float = (oversteer_amount - esp.yaw_threshold) * esp.yaw_correction_rate
		brake_amount = clampf(brake_amount, 0.0, 1.0)
		_esp_brake_role("front", -steer_sign, brake_amount)
		intervened = true
	elif -oversteer_amount > esp.stabilization_threshold:
		# Understeer (yaw error opposes steer direction beyond threshold).
		# Brake the INNER REAR — same side as steer_sign.
		var slip: float = -oversteer_amount - esp.stabilization_threshold
		var brake_amount: float = slip * esp.correction_rate
		brake_amount = clampf(brake_amount, 0.0, 1.0)
		_esp_brake_role("rear", steer_sign, brake_amount)
		intervened = true
	
	espflash = intervened


## Helper: applies tc_brake to the wheel whose ESP_Role matches the given
## axle ("front"/"rear") and whose local-x sign matches the given side sign.
## side_sign > 0 picks the +x side wheel; side_sign < 0 picks the -x side.
func _esp_brake_role(axle: String, side_sign: float, amount: float) -> void:
	if amount <= 0.0:
		return
	for child in get_children():
		if not "ESP_Role" in child:
			continue
		var role: String = String(child.ESP_Role)
		if role.is_empty():
			continue
		# Match by substring so users can label "front_left", "FrontLeft", etc.
		var lower: String = role.to_lower()
		if not lower.contains(axle):
			continue
		# Determine the wheel's side from its local x position. This avoids
		# trusting a string like "left"/"right" being authored consistently.
		var x: float = (child as Node3D).position.x if child is Node3D else 0.0
		if signf(x) != signf(side_sign):
			continue
		if "tc_brake" in child:
			child.tc_brake = maxf(child.tc_brake, amount)


func apply_clutch_wear():
	pass # Future mechanic. Clutch wears over time, this calculates how much wear and applies its reduced effect.


func shift_up():
	pass


func shift_down():
	pass


func simulate_physical_steering():
	final_steer += steer_velocity
	
	if abs(final_steer) > 1.0:
		steer_velocity *= -0.5
	
	for i in [$fl,$fr]:
		steer_velocity += (i.directional_force.x * 0.00125) * i.Caster
		steer_velocity -= (i.stress * 0.0025) * (atan2(abs(i.wv), 1.0) * i.angle)
		
		steer_velocity += final_steer * (i.directional_force.z * 0.0005) * i.Caster
		
		if i.position.x > 0:
			steer_velocity += i.directional_force.z * 0.0001
		else:
			steer_velocity -= i.directional_force.z * 0.0001
		
		steer_velocity /= i.stress / (pow(i.slip_percpre, 2) * 100.0 + 1.0) + 1.0


func control_car():
	var left := Input.is_action_pressed("left")
	var right := Input.is_action_pressed("right")
	
	if ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.FULL:
		if gas and not gasrestricted and not gear == -1 or brake and gear == -1 or revmatch:
			gaspedal += ConfigManager.data.controls.on_throttle_rate / clock_mult
		else:
			gaspedal -= ConfigManager.data.controls.off_throttle_rate / clock_mult
		
		if brake and not gear == -1 or gas and gear == -1:
			brakepedal += ConfigManager.data.controls.on_brake_rate / clock_mult
		else:
			brakepedal -= ConfigManager.data.controls.off_brake_rate / clock_mult
	else:
		if ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.NONE:
			gasrestricted = false
			clutchin = false
			revmatch = false
		
		if gas and not gasrestricted or revmatch:
			gaspedal += ConfigManager.data.controls.on_throttle_rate / clock_mult
		else:
			gaspedal -= ConfigManager.data.controls.off_throttle_rate / clock_mult
		
		if brake:
			brakepedal += ConfigManager.data.controls.on_brake_rate / clock_mult
		else:
			brakepedal -= ConfigManager.data.controls.off_brake_rate / clock_mult
	
	if handbrake:
		handbrakepull += ConfigManager.data.controls.on_handbrake_rate / clock_mult
	else:
		handbrakepull -= ConfigManager.data.controls.off_handbrake_rate / clock_mult
	
	## Sideways movement.
	var siding := absf(velocity.x)
	
	if velocity.x > 0 and steer_target > 0 or velocity.x < 0 and steer_target < 0:
		siding = 0.0
	
	var going := velocity.z / (siding + 1.0)
	going = max(going, 0.0)
	
	var mouseposx = 0.0
	if get_viewport().size.x > 0.0:
		mouseposx = get_viewport().get_mouse_position().x / get_viewport().size.x
	
	if LooseSteering: return
	
	if ConfigManager.data.controls.mouse_steering:
		steer_target = (mouseposx - 0.5) * 2.0 * ConfigManager.data.controls.steering_sensitivity
		
		var s := absf(steer_target) * 1.0 + 0.5
		s = min(s, 1.0)
		
		steer_target *= s
	elif ConfigManager.data.controls.accelerometer_steering:
		steer_target = (Input.get_accelerometer().x / 10.0) * ConfigManager.data.controls.steering_sensitivity
		
		var s := absf(steer_target) * 1.0 + 0.5
		s = min(s, 1.0)
		
		steer_target *= s
	
	else:
		if right:
			if steer_target > 0:
				steer_target += ConfigManager.data.controls.keyboard_steer_speed
			else:
				steer_target += ConfigManager.data.controls.keyboard_compensate_speed
		elif left:
			if steer_target < 0:
				steer_target -= ConfigManager.data.controls.keyboard_steer_speed
			else:
				steer_target -= ConfigManager.data.controls.keyboard_compensate_speed
		else:
			if steer_target > ConfigManager.data.controls.keyboard_return_speed:
				steer_target -= ConfigManager.data.controls.keyboard_return_speed
			elif steer_target < -ConfigManager.data.controls.keyboard_return_speed:
				steer_target += ConfigManager.data.controls.keyboard_return_speed
			else:
				steer_target = 0.0
	
	if assistance_factor > 0.0:
		var maxsteer := 1.0 / (going * (ConfigManager.data.controls.steer_amount_decay / assistance_factor) + 1.0)
		
		var assist_commence := linear_velocity.length() / 10.0
		assist_commence = min(assist_commence, 1.0)
		
		final_steer = (steer_target * maxsteer) - (velocity.normalized().x * assist_commence) * (ConfigManager.data.controls.steering_assistance * assistance_factor) + rvelocity.y * (ConfigManager.data.controls.steering_assistance_angular * assistance_factor)
	else:
		final_steer = steer_target


func simulate_manual():
	if clutch and not clutchin:
		clutchpedalreal -= ConfigManager.data.controls.off_clutch_rate / clock_mult
	else:
		clutchpedalreal += ConfigManager.data.controls.on_clutch_rate / clock_mult
	
	clutchpedal = 1.0 - clutchpedalreal
	
	if gear > 0:
		ratio = GearRatios[gear-1] * final_drive * ratio_multi
	elif gear == -1:
		ratio = reverse_ratio * final_drive * ratio_multi
	
	if ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.NONE:
		if input_upshift:
			input_upshift = false
			if gear < len(GearRatios):
				if gearstress < GearGap:
					actualgear += 1
		if input_downshift:
			input_downshift = false
			if gear > -1 and gearstress < GearGap:
				actualgear -= 1
	elif ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.WEAK:
		if rpm < shift_assist.clutch_out_rpm:
			var irga_ca = (shift_assist.clutch_out_rpm - rpm) / (shift_assist.clutch_out_rpm - IdleRPM)
			clutchpedalreal = pow(irga_ca, 2)
		elif not gasrestricted and not revmatch:
			clutchin = false
		if input_upshift:
			input_upshift = false
			if gear < len(GearRatios):
				if rpm < shift_assist.clutch_out_rpm:
					actualgear += 1
				else:
					if actualgear < 1:
						actualgear += 1
						if rpm > shift_assist.clutch_out_rpm:
							clutchin = false
					else:
						if shift_assist_delay > 0:
							actualgear += 1
						shift_assist_delay = int(shift_assist.shift_delay / 2.0)
						sassiststep = -4
						
						clutchin = true
						gasrestricted = true
		elif input_downshift:
			input_downshift = false
			if gear > -1:
				if rpm < shift_assist.clutch_out_rpm:
					actualgear -= 1
				else:
					if actualgear == 0 or actualgear == 1:
						actualgear -= 1
						clutchin = false
					else:
						if shift_assist_delay > 0:
							actualgear -= 1
						shift_assist_delay = int(shift_assist.shift_delay / 2.0)
						sassiststep = -2
						
						clutchin = true
						revmatch = true
						gasrestricted = false
	elif ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.FULL:
		var assistshiftspeed = (shift_assist.upshift_rpm / ratio) * drivewheels_size
		var assistdownshiftspeed = (shift_assist.downshift_rpm / abs((GearRatios[gear-2] * final_drive) * ratio_multi)) * drivewheels_size
		if gear == 0:
			if gas:
				shift_assist_delay -= 1
				if shift_assist_delay < 0:
					actualgear = 1
			elif brake:
				shift_assist_delay -= 1
				if shift_assist_delay < 0:
					actualgear = -1
			else:
				shift_assist_delay = 60
		elif linear_velocity.length()<5:
			if not gas and gear == 1 or not brake and gear == -1:
				shift_assist_delay = 60
				actualgear = 0
		if sassiststep == 0:
			if rpm<shift_assist.clutch_out_rpm:
				var irga_ca = (shift_assist.clutch_out_rpm - rpm)/(shift_assist.clutch_out_rpm - IdleRPM)
				clutchpedalreal = pow(irga_ca, 2)
			else:
				clutchin = false
			if not gear == -1:
				if gear < len(GearRatios) and linear_velocity.length() > assistshiftspeed:
					shift_assist_delay = int(shift_assist.shift_delay / 2.0)
					sassiststep = -4
					
					clutchin = true
					gasrestricted = true
				if gear>1 and linear_velocity.length()<assistdownshiftspeed:
					shift_assist_delay = int(shift_assist.shift_delay / 2.0)
					sassiststep = -2
					
					clutchin = true
					gasrestricted = false
					revmatch = true
	
	if sassiststep == -4 and shift_assist_delay < 0:
		shift_assist_delay = int(shift_assist.shift_delay / 2.0)
		if gear<len(GearRatios):
			actualgear += 1
		sassiststep = -3
	elif sassiststep == -3 and shift_assist_delay < 0:
		if rpm > shift_assist.clutch_out_rpm:
			clutchin = false
		if shift_assist_delay < -shift_assist.post_shift_delay:
			sassiststep = 0
			gasrestricted = false
	elif sassiststep == -2 and shift_assist_delay < 0:
		sassiststep = 0
		if gear > -1:
			actualgear -= 1
		if rpm > shift_assist.clutch_out_rpm:
			clutchin = false
		gasrestricted = false
		revmatch = false
	
	gear = actualgear


func simulate_automatic_gearbox():
	clutchpedal = (rpm - auto_gearbox.engagement_min_rpm * (gaspedal * auto_gearbox.throttle_threshold + (1.0 - auto_gearbox.throttle_threshold) ) ) / auto_gearbox.engagement_max_rpm
	
	if not ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.FULL:
		if input_upshift:
			input_upshift = false
			if gear < 1:
				actualgear += 1
		if input_downshift:
			input_downshift = false
			if gear > -1:
				actualgear -= 1
	else:
		if gear == 0:
			if gas:
				shift_assist_delay -= 1
				if shift_assist_delay < 0:
					actualgear = 1
			elif brake:
				shift_assist_delay -= 1
				if shift_assist_delay < 0:
					actualgear = -1
			else:
				shift_assist_delay = 60
		elif linear_velocity.length() < 5:
			if not gas and gear == 1 or not brake and gear == -1:
				shift_assist_delay = 60
				actualgear = 0
	
	if actualgear == -1:
		ratio = reverse_ratio * final_drive * ratio_multi
	else:
		ratio = GearRatios[gear-1] * final_drive * ratio_multi
	if actualgear>0:
		var lastratio = GearRatios[gear-2] * final_drive * ratio_multi
		input_upshift = false
		input_downshift = false
		for i in c_pws:
			if (i.wv / drivewheels_size) > (auto_gearbox.upshift_rpm * (gaspedal * auto_gearbox.throttle_threshold + (1.0 - auto_gearbox.throttle_threshold))) / ratio:
				input_upshift = true
			elif (i.wv / drivewheels_size) < ((auto_gearbox.upshift_rpm - auto_gearbox.downshift_threshold) * (gaspedal * auto_gearbox.throttle_threshold + (1.0 - auto_gearbox.throttle_threshold))) /lastratio:
				input_downshift = true
		if input_upshift:
			gear += 1
		elif input_downshift:
			gear -= 1
		
		gear = clamp(gear, 1, len(GearRatios))
	else:
		gear = actualgear


func simulate_cvt():
	clutchpedal = (rpm - auto_gearbox.engagement_min_rpm * (gaspedal * auto_gearbox.throttle_threshold + (1.0 - auto_gearbox.throttle_threshold) ) ) / auto_gearbox.engagement_max_rpm
	
	if not ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.FULL:
		if input_upshift:
			input_upshift = false
			if gear < 1:
				actualgear += 1
		if input_downshift:
			input_downshift = false
			if gear > -1:
				actualgear -= 1
	else:
		if gear == 0:
			if gas:
				shift_assist_delay -= 1
				if shift_assist_delay<0:
					actualgear = 1
			elif brake:
				shift_assist_delay -= 1
				if shift_assist_delay<0:
					actualgear = -1
			else:
				shift_assist_delay = 60
		elif linear_velocity.length() < 5:
			if not gas and gear == 1 or not brake and gear == -1:
				shift_assist_delay = 60
				actualgear = 0
	
	gear = actualgear
	var wv := 0.0
	
	for i in c_pws:
		wv += i.wv / len(c_pws)
	
	cvtaccel -= (cvtaccel - (gaspedal * cvt.efficiency_range +(1.0-cvt.efficiency_range)))*cvt.ratio_step_rate
	
	var a := cvt.lock_timing / ( (absf(wv) / 10.0) * cvtaccel + 1.0)
	
	a = max(a, cvt.stability_damping)
	
	ratio = (cvt.rpm_offset * 10000000.0) / (abs(wv) * (rpm * a) + 1.0)
	ratio = min(ratio, cvt.standstill_torque)


func simulate_semi_auto_gearbox():
	clutchpedal = (rpm - auto_gearbox.engagement_min_rpm * (gaspedal * auto_gearbox.throttle_threshold + (1.0 - auto_gearbox.throttle_threshold) ) ) / auto_gearbox.engagement_max_rpm
	
	if gear > 0:
		ratio = GearRatios[gear-1] * final_drive * ratio_multi
	elif gear == -1:
		ratio = reverse_ratio * final_drive * ratio_multi
	
	if ConfigManager.data.controls.shift_assist_level < ControlsConfig.ShiftAssistLevel.FULL:
		if input_upshift:
			input_upshift = false
			if gear < len(GearRatios):
				actualgear += 1
		if input_downshift:
			input_downshift = false
			if gear > -1:
				actualgear -= 1
	else:
		var assistshiftspeed := (shift_assist.upshift_rpm / ratio) * drivewheels_size
		var assistdownshiftspeed = (shift_assist.downshift_rpm / abs((GearRatios[gear-2] * final_drive) * ratio_multi)) * drivewheels_size
		if gear == 0:
			if gas:
				shift_assist_delay -= 1
				if shift_assist_delay<0:
					actualgear = 1
			elif brake:
				shift_assist_delay -= 1
				if shift_assist_delay<0:
					actualgear = -1
			else:
				shift_assist_delay = 60
		elif linear_velocity.length() < 5:
			if not gas and gear == 1 or not brake and gear == -1:
				shift_assist_delay = 60
				actualgear = 0
		if sassiststep == 0:
			if not gear == -1:
				if gear < len(GearRatios) and linear_velocity.length() > assistshiftspeed:
					actualgear += 1
				if gear > 1 and linear_velocity.length() < assistdownshiftspeed:
					actualgear -= 1
	
	gear = actualgear


func bullet_fix():
	var offset = $DRAG_CENTRE.position
	AckermannPoint -= offset.z
	
	for i in get_children():
		i.position -= offset


func controls():
	# IMPORTANT: Why if else in controls and in transmission?
	if ConfigManager.data.controls.mouse_steering:
		gas = Input.is_action_pressed("gas_mouse")
		brake = Input.is_action_pressed("brake_mouse")
		input_upshift = Input.is_action_just_pressed("shiftup_mouse")
		input_downshift = Input.is_action_just_pressed("shiftdown_mouse")
		handbrake = Input.is_action_pressed("handbrake_mouse")
	else:
		gas = Input.is_action_pressed("gas")
		brake = Input.is_action_pressed("brake")
		input_upshift = Input.is_action_just_pressed("shiftup")
		input_downshift = Input.is_action_just_pressed("shiftdown")
		handbrake = Input.is_action_pressed("handbrake")
	
	steer_velocity += 0.01 * Input.get_axis("left", "right")
	
	if LooseSteering:
		simulate_physical_steering()
	
	if Controlled:
		control_car()


func transmission():
	if Controlled:
		clutch = Input.is_action_pressed("clutch") and not ConfigManager.data.controls.mouse_steering or Input.is_action_pressed("clutch_mouse") and ConfigManager.data.controls.mouse_steering
		if not ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.NONE:
			clutch = Input.is_action_pressed("handbrake") and not ConfigManager.data.controls.mouse_steering or Input.is_action_pressed("handbrake_mouse") and ConfigManager.data.controls.mouse_steering
		clutch = !clutch
	
	if transmission_type == TransmissionType.FULLY_MANUAL:
		simulate_manual()
	elif transmission_type == TransmissionType.AUTOMATIC:
		simulate_automatic_gearbox()
	elif transmission_type == TransmissionType.CONTINUOUSLY_VARIABLE:
		simulate_cvt()
	elif transmission_type == TransmissionType.SEMI_AUTO:
		simulate_semi_auto_gearbox()


func drivetrain():
	rpmcsm -= (rpmcs - resistance)
	rpmcs += rpmcsm*ClutchElasticity
	rpmcs -= rpmcs * (1.0 - clutchpedal)
	wob = ClutchWobble * clutchpedal
	wob *= ratio * WobbleRate
	rpmcs -= (rpmcs - resistance) * (1.0 / (wob + 1.0) )
	
	var rpm_change := ((rpmcs * 1.0) / clock_mult) * (RevSpeed / Constants.REVSPEED_TUNE)
	if gear < 0:
		rpm -= rpm_change
	else:
		rpm += rpm_change
	
	gearstress = (abs(resistance) * StressFactor) * clutchpedal
	var stabled := ratio * 0.9 + 0.1
	ds_weight = DSWeight / stabled
	
	whinepitch = abs(rpm / ratio) * 1.5
	
	if resistance > 0.0:
		locked = abs(resistance / ds_weight) * (CoastLocking / 100.0) + Preload
	else:
		locked = abs(resistance / ds_weight) * (Locking / 100.0) + Preload
	
	locked = clamp(locked, 0.0, 1.0)
	
	
	if wv_difference > 0.0:
		c_locked = abs(wv_difference) * (Centre_CoastLocking / 10.0) + Centre_Preload
	else:
		c_locked = abs(wv_difference) * (Centre_Locking / 10.0) + Centre_Preload
	if len(c_pws) < 4:
		c_locked = 0.0
	c_locked = clamp(c_locked, 0.0, 1.0)
	
	var maxd = VitaVehicleSimulation.fastest_wheel(c_pws)
	#var mind = VitaVehicleSimulation.slowest_wheel(c_pws)
	var what := 0.0
	
	var floatreduction := ClutchFloatReduction
	
	if dsweightrun > 0.0:
		floatreduction = ClutchFloatReduction / dsweightrun
	else:
		floatreduction = 0.0
	
	var stabling := -(GearRatioRatioThreshold - ratio * drivewheels_size) * ThresholdStable
	stabling = max(stabling, 0.0)
	
	currentstable = ClutchStable + stabling
	currentstable *= (RevSpeed / Constants.REVSPEED_TUNE)
	
	if dsweightrun > 0.0:
		what = (rpm - (((rpmforce * floatreduction) * currentstable) / (ds_weight / dsweightrun)))
	else:
		what = rpm
	
	if gear < 0.0:
		dist = maxd.wv + what / ratio
	else:
		dist = maxd.wv - what / ratio
	
	dist *= pow(clutchpedal, 2)
	
	if gear == 0:
		dist = 0.0
	
	wv_difference = 0.0
	drivewheels_size = 0.0
	for i in c_pws:
		drivewheels_size += i.w_size / len(c_pws)
		i.c_p = i.W_PowerBias
		wv_difference += ((i.wv - what / ratio) / (len(c_pws))) * pow(clutchpedal, 2)
		if gear < 0:
			i.dist = dist * (1 - c_locked) + (i.wv + what / ratio) * c_locked
		elif gear > 0:
			i.dist = dist * (1 - c_locked) + (i.wv - what / ratio) * c_locked
		else:
			i.dist = 0.0
	
	resistance = 0.0
	dsweightrun = dsweight
	dsweight = 0.0
	tcsweight = 0.0
	stress = 0.0


func simulate_fuel():
	if !fuel: return
	
	# New BSFC-based API: pass the whole car so the model can read throttle,
	# AFR target, boost, gear, clutch state etc. The fuel resource handles
	# DFCO/ignition internally. Older Fuel resources without the new fields
	# still work because their idle_consumption export is preserved.
	var fuel_consumption: float = fuel.get_consumption(self)
	
	current_fuel -= fuel_consumption * get_physics_process_delta_time()
	
	if current_fuel <= 0.0:
		current_fuel = 0.0
		stop_engine()


func aero():
	var drag := DragCoefficient
	var df := Downforce
	
	var veloc := global_transform.basis.orthonormalized().transposed() * (linear_velocity)
	
	#var torq := global_transform.basis.orthonormalized().transposed() * (Vector3(1, 0, 0))
	
	apply_torque_impulse(global_transform.basis.orthonormalized() * ( Vector3(((-veloc.length()*0.3)*LiftAngle), 0, 0)  ) )
	
	# TODO: Extract magic value.
	var vx := veloc.x * 0.15
	var vy := veloc.z * 0.15
	var vz := veloc.y * 0.15
	var vl := veloc.length() * 0.15
	
	var forc := global_transform.basis.orthonormalized() * Vector3(-vx * drag, -vl * df -vz * drag, -vy * drag)
	
	if has_node("DRAG_CENTRE"):
		apply_impulse(forc, global_transform.basis.orthonormalized() * ($DRAG_CENTRE.position))
	else:
		apply_central_impulse(forc)


func draw_debug():
	# BUG: Why do this each frame? Initialize with events no?
		front_wheels = []
		rear_wheels = []
		for i in get_children():
			if "TyreSettings" in i:
				if i.position.z > 0: # IMPORTANT: So weird to check by distance. What if an origin is shifted?
					front_wheels.append(i)
				else:
					rear_wheels.append(i)
		
		front_load = 0.0
		total = 0.0
		
		for f in front_wheels:
			front_load += f.directional_force.y
			total += f.directional_force.y
		for r in rear_wheels:
			front_load -= r.directional_force.y
			total += r.directional_force.y
		
		if total > 0:
			weight_dist[0] = remap(front_load / total, -1.0, 1.0, 0.0, 1.0)
			weight_dist[1] = 1.0 - weight_dist[0]


func start_engine():
	# TODO: This ignites the engine back up, make it more... natural. WARNING: Don't assume i start from 0.
	rpm = max(rpm, IdleRPM)
	is_ignition_on = true


func stop_engine():
	is_ignition_on = false


func is_above_idle_rpm():
	return rpm > IdleRPM


## Asks [code]CarManager[/code] (if present) to hand control to this car.
## No-op when the autoload isn't configured.
func make_active() -> void:
	var cm := _find_car_manager()
	if cm != null:
		cm.call("set_active", self)
	else:
		Controlled = true
