class_name Car extends RigidBody3D



signal debug_lamp_changed



enum TransmissionType {FULLY_MANUAL, AUTOMATIC, CONTINUOUSLY_VARIABLE, SEMI_AUTO}



@export_group("Profiles")
@export var fuel: Fuel

@export_subgroup("Gearbox")
@export var shift_assist: ShiftAssistProfile
@export var auto_gearbox: AutoGearboxProfile
@export var cvt: CVTProfile

@export_subgroup("Stability")
## Anti-lock Braking System.
@warning_ignore("shadowed_global_identifier")
@export var abs: ABSProfile
## Electronic Stability Program.
@export var esp := ESPProfile
## Brake-based Traction Control System.
@export var btcs := BTCSProfile
## Throttle-based Traction Control System
@export var ttcs := TTCSProfile

@export_group("Other")
@export var Debug_Mode := false
@export var LooseSteering := false #simulate rack and pinion steering physics (EXPERIMENTAL) # May belong in ControlsConfig, unsure.
# meta
@export var Controlled := true

@export_group("Chassis")
@export_custom(PROPERTY_HINT_NONE, "suffix:kg") var Weight := 900.0

@export_group("Body")
@export var LiftAngle := 0.1
@export var DragCoefficient := 0.25
@export var Downforce := 0.0

@export_group("Steering")
@export var AckermannPoint := -3.8
@export var Steer_Radius := 13.0

@export_group("Drivetrain")
@export var Powered_Wheels: Array[String] = ["fl","fr"]

## Ratio multiplier of the gearbox.
@export var final_drive := 4.250
## Ratios of forward gears.
@export var GearRatios: Array[float] = [ 3.250, 1.894, 1.259, 0.937, 0.771 ]
## Ratio of reverse gear.
@export var reverse_ratio := 3.153
## Ratio multiplier of the drivetrain.
@export var ratio_multi := 9.5 # Useless, basically final_drive_2
@export var StressFactor := 1.0
@export var GearGap := 60.0
@export var DSWeight := 150.0 # Leave this be, unless you know what you're doing.

@export var transmission_type := TransmissionType.FULLY_MANUAL

@export_group("Differentials")
@export var Locking := 0.1
@export var CoastLocking := 0.0
@export var Preload := 0.0
@export var Centre_Locking := 0.5
@export var Centre_CoastLocking := 0.5
@export var Centre_Preload := 0.0

@export_group("Engine")
## Flywheel lightness.
@export var RevSpeed := 2.0
@export var EngineFriction := 18000.0
@export var EngineDrag := 0.006
@export var ThrottleResponse := 0.5
@export var DeadRPM := 200.0

@export_group("ECU")
@export var RPMLimit := 7000.0
@export var LimiterDelay := 4
@export var IdleRPM := 800.0
@export var ThrottleLimit := 0.0
@export var ThrottleIdle := 0.25
@export var VVTRPM := 4500.0 # set this beyond the rev range to disable it, set it to 0 to use this vvt state permanently

@export_group("Torque normal state")
@export var BuildUpTorque := 0.0035
@export var TorqueRise := 30.0
@export var RiseRPM := 1000.0
@export var OffsetTorque := 110.0
@export var FloatRate := 0.1
@export var DeclineRate := 1.5
@export var DeclineRPM := 3500.0
@export var DeclineSharpness := 1.0

@export_group("Torque variable valve timing")
@export var VVT_BuildUpTorque := 0.0
@export var VVT_TorqueRise := 60.0
@export var VVT_RiseRPM := 1000.0
@export var VVT_OffsetTorque := 70.0
@export var VVT_FloatRate := 0.1
@export var VVT_DeclineRate := 2.0
@export var VVT_DeclineRPM := 5000.0
@export var VVT_DeclineSharpness := 1.0

@export_group("Clutch")
@export var ClutchStable := 0.5
@export var GearRatioRatioThreshold := 200.0
@export var ThresholdStable := 0.01
@export var ClutchGrip := 176.125
@export var ClutchFloatReduction := 27.0
@export var ClutchWobble := 2.5*0
@export var ClutchElasticity := 0.2*0
@export var WobbleRate := 0.0

@export_group("Forced inductions")
@export var MaxPSI := 9.0 # Maximum air generated by any forced inductions
@export var EngineCompressionRatio := 8.0 # Piston travel distance
@export_subgroup("Turbo")
@export_custom(PROPERTY_HINT_GROUP_ENABLE, "Turbo") var TurboEnabled := false
@export var TurboAmount := 1 # Turbo power multiplication.
@export var TurboSize := 8.0 # Higher = More turbo lag
@export var Compressor := 0.3 # Higher = Allows more spooling on low RPM
@export var SpoolThreshold := 0.1 # Range: 0 - 0.9999
@export var BlowoffRate := 0.14
@export var TurboEfficiency := 0.075 # Range: 0 - 1
@export var TurboVacuum := 1.0 # Performance deficiency upon turbo idle
@export_subgroup("Supercharger")
@export_custom(PROPERTY_HINT_GROUP_ENABLE, "Supercharger") var SuperchargerEnabled := false
@export var SCRPMInfluence := 1.0
@export var BlowRate := 35.0
@export var SCThreshold := 6.0

## Current RPM.
var rpm := 0.0
var rpmspeed := 0.0
var resistancerpm := 0.0
var resistancedv := 0.0
## Current transmission gear.
var gear := 0
var limiter_delay := 0
var actualgear := 0
var gearstress := 0.0
## Actual engine throttle.
var throttle := 0.0:
	set(value): throttle = clamp(value, 0.0, 1.0)
var cvtaccel := 0.0
var shift_assist_delay := 0
## Shift assist step.
var sassiststep := 0
var clutchin := false
var gasrestricted := false
var revmatch := false
## Throttle input.
var gaspedal := 0.0:
	set(value): gaspedal = clamp(value, 0.0, ConfigManager.data.controls.max_throttle)
var brakepedal := 0.0:
	set(value): brakepedal = clamp(value, 0.0, ConfigManager.data.controls.max_brake)
var clutchpedal := 0.0:
	set(value): clutchpedal = clamp(value, 0.0, 1.0)
var clutchpedalreal := 0.0:
	set(value): clutchpedalreal = clamp(value, 0.0, ConfigManager.data.controls.max_clutch)
## Final steering target after assists and decay.
var final_steer := 0.0:
	set(value): final_steer = clamp(value, -1.0, 1.0)
## Raw steering target from key/mouse/accel input.
var steer_target := 0.0:
	set(value): steer_target = clamp(value, -1.0, 1.0)
var abs_delay := 0.0
var tcsweight := 0.0
var tcsflash := false
var espflash := false
## Current gear ratio (gear * final_drive).
var ratio := 0.0
var brake_allowed := 1.0
## Real engine torque.
var engine_torque := 0.0
## Does the engine inject and ignite fuel?
var is_ignition_on := true
## The amount of vaccuum.
var stall_resistance := 0.0

## Final brake pressure.
var brakeline := 0.0
var handbrakepull := 0.0:
	set(value): handbrakepull = clamp(value, 0.0, ConfigManager.data.controls.max_handbrake)
var dsweight := 0.0
var dsweightrun := 0.0
var diffspeed := 0.0
var diffspeedun := 0.0
var locked := 0.0
var c_locked := 0.0
var wv_difference := 0.0
var rpmforce := 0.0
var whinepitch := 0.0
var turbopsi := 0.0
var scrpm := 0.0
var boosting := 0.0
var rpmcs := 0.0
var rpmcsm := 0.0
var currentstable := 0.0
var steering_geometry := [0.0, 0.0]
var resistance := 0.0
var wob := 0.0
var ds_weight := 0.0
var steer_torque := 0.0
var steer_velocity := 0.0
var drivewheels_size := 1.0

var steering_angles := []
var max_steering_angle := 0.0
var assistance_factor := 0.0



var pastvelocity := Vector3(0, 0, 0)
var gforce := Vector3(0, 0, 0)
var clock_mult := 1.0
var dist := 0.0
var stress := 0.0

# control flags
## Input shift up.
var input_upshift := false
## Input shift down.
var input_downshift := false
var gas := false
var brake := false
var handbrake := false
var clutch := false
## Powered wheel nodes.
var c_pws := []

var velocity := Vector3(0, 0, 0)
var rvelocity := Vector3(0, 0, 0)

# draw debug
var front_wheels := []
var rear_wheels := []
var front_load := 0.0
var total := 0.0
var weight_dist := [0.0, 0.0]

var debug_lamp := false:
	set(value): debug_lamp = value; debug_lamp_changed.emit()

## The current amount of fuel in [code]liters[/code].
@onready var current_fuel := fuel.max_fuel



#region internal
func _input(event: InputEvent) -> void:
	if event.is_action_pressed("toggle_debug_mode"):
		Debug_Mode = !Debug_Mode
	if event.is_action_pressed("ignition"):
		if is_ignition_on: stop_engine()
		else: start_engine()


func _ready():
	#bullet_fix()
	# Multi-car: register with the manager (if the autoload is configured) so
	# the active car can be tracked and cycled. Resolved by-name to avoid a
	# compile dependency on the autoload.
	var car_manager := _find_car_manager()
	if car_manager != null:
		car_manager.call("register", self)
	# Auto-start the engine for spark engines (you turn the key) and for
	# diesels that are already cranking above their auto-ignition threshold.
	# The fuel resource may be null in tests; default to spark behavior.
	var should_start := true
	if fuel != null and "ignition_type" in fuel:
		# COMPRESSION = 1 in the IgnitionType enum on Fuel. Compare by value
		# rather than the symbol so older Fuel resources (without the field)
		# don't blow up.
		if fuel.ignition_type == 1:  # IgnitionType.COMPRESSION
			should_start = fuel.should_compression_autostart(rpm)
	if should_start:
		start_engine()
	for i in Powered_Wheels:
		var wh := get_node(i)
		c_pws.append(wh)


func _find_car_manager() -> Node:
	# CarManager is set up as an autoload (Project Settings → Autoload).
	# Resolved by-name so this script still loads if the autoload isn't wired.
	if get_tree() == null:
		return null
	var root := get_tree().root
	if root.has_node("CarManager"):
		return root.get_node("CarManager")
	return null


func _process(_delta):
	if Debug_Mode: draw_debug()


func _physics_process(delta):
	if len(steering_angles) > 0:
		max_steering_angle = 0.0
		for i in steering_angles:
			max_steering_angle = maxf(max_steering_angle, i)
			
		assistance_factor = 90.0 / max_steering_angle
	steering_angles = []
	
	velocity = global_transform.basis.orthonormalized().transposed() * (linear_velocity)
	rvelocity = global_transform.basis.orthonormalized().transposed() * (angular_velocity)
	
	mass = Weight / 10.0 # Shouldn't this be the gravity?
	aero()
	
	gforce = (linear_velocity - pastvelocity) * ((Constants.UNIT_TO_METER / Physics.EARTH_GRAVITY) / delta)
	pastvelocity = linear_velocity
	
	gforce = global_transform.basis.orthonormalized().transposed() * gforce
	
	controls()
	
	ratio = 10.0
	
	shift_assist_delay -= 1
	
	transmission()
	
	var steeroutput := final_steer
	
	## Reduces steering sensitivity as you approach max angle.
	var steer_reduction := pow(max_steering_angle / 90.0, 2) * 0.5
	steeroutput *= abs(final_steer) * (steer_reduction) + (1.0 - steer_reduction)
	
	if abs(steeroutput) > 0.0:
		steering_geometry = [-Steer_Radius / steeroutput, AckermannPoint]
	
	
	if abs: apply_abs()
	
	brakeline = brakepedal * brake_allowed
	
	brakeline = max(brakeline, 0.0)
	
	
	if !is_redline_limiter_on():
		throttle -= (throttle - (gaspedal / (tcsweight * clutchpedal + 1.0) ) ) * (ThrottleResponse / clock_mult)
	else:
		throttle -= throttle * (ThrottleResponse / clock_mult)
	
	apply_redline_limiter()
	apply_idle_throttle_compensation()
	simulate_turbo()
	#var stab := 300.0 # What is this? Remove it? Stab for stability? Some sort of stability strength level?
	simulate_engine()
	drivetrain()
	simulate_fuel()
#endregion internal


func toggle_ignition():
	if is_ignition_on:
		stop_engine()
	else:
		start_engine()


## Is variable valve timing activated?
func is_vvt_active():
	return rpm > VVTRPM


func is_redline_limiter_on():
	return limiter_delay > 0


func is_in_gear():
	return actualgear != 0


func is_throttle_open():
	return throttle > 0.0


func apply_redline_limiter():
	if rpm > RPMLimit and throttle > ThrottleLimit:
		throttle = ThrottleLimit
		limiter_delay = LimiterDelay
	
	limiter_delay -= 1


func apply_idle_throttle_compensation():
	if rpm < IdleRPM:
		throttle = clamp(throttle, ThrottleIdle + ( (IdleRPM - rpm) / IdleRPM), 1.0)
		# The farther from idle, the higher the throttle.
		# TODO: Swap this out for a curve resource.


func simulate_turbo():
	var thr := 0.0
	
	if TurboEnabled:
		thr = (throttle - SpoolThreshold) / (1 - SpoolThreshold)
			
		if boosting > thr:
			boosting = thr
		else:
			boosting -= (boosting - thr) * TurboEfficiency
		
		turbopsi += (boosting * rpm) / ( (TurboSize / Compressor) * 60.9)
		
		turbopsi -= turbopsi * BlowoffRate
		turbopsi = clamp(turbopsi, -TurboVacuum, MaxPSI)
	elif SuperchargerEnabled:
		scrpm = rpm * SCRPMInfluence
		turbopsi = (scrpm / 10000.0) * BlowRate - SCThreshold
		turbopsi = clamp(turbopsi, 0.0, MaxPSI)
	else:
		turbopsi = 0.0


func simulate_engine():
	var torque := 0.0
	
	# Diesel: if the engine is off but the wheels are turning the crank fast
	# enough (clutch engaged in gear, push-start, etc.), it self-ignites.
	if !is_ignition_on and fuel != null and "ignition_type" in fuel:
		if fuel.ignition_type == 1 and fuel.should_compression_autostart(rpm):
			if current_fuel > 0.0:
				start_engine()
	
	if !is_ignition_on:
		throttle = 0.0
		turbopsi = 0.0
	elif is_vvt_active():
		var f := rpm - VVT_RiseRPM
		f = max(f, 0.0)
		torque = (rpm * VVT_BuildUpTorque + VVT_OffsetTorque + pow(f, 2) * (VVT_TorqueRise * Constants.RISE_FACTOR)) * throttle
		torque += ( (turbopsi * TurboAmount) * (EngineCompressionRatio * 0.609) )
		var j := rpm - VVT_DeclineRPM
		j = max(j, 0.0)
		torque /= (j * (j * VVT_DeclineSharpness + (1.0 - VVT_DeclineSharpness) ) ) * (VVT_DeclineRate * Constants.RISE_FACTOR) + 1.0
		torque /= pow(abs(rpm), 2) * (VVT_FloatRate * Constants.RISE_FACTOR) + 1.0
	else:
		var f := rpm - RiseRPM
		f = max(f, 0.0)
		torque = (rpm * BuildUpTorque + OffsetTorque + pow(f, 2) * (TorqueRise * Constants.RISE_FACTOR)) * throttle
		torque += ( (turbopsi * TurboAmount) * (EngineCompressionRatio * 0.609) )
		var j := rpm - DeclineRPM
		j = max(j, 0.0)
		torque /= (j * (j * DeclineSharpness + (1.0 - DeclineSharpness) ) ) * (DeclineRate * Constants.RISE_FACTOR) + 1.0
		torque /= pow(abs(rpm), 2) * (FloatRate * Constants.RISE_FACTOR) + 1.0
	
	rpmforce = (rpm / (pow(abs(rpm), 2) / (EngineFriction / clock_mult) + 1.0)) * 1.0
	if rpm < DeadRPM:
		stop_engine()
		torque = 0.0
		rpmforce /= 5.0
		stall_resistance = 1.0 - rpm / DeadRPM
	else:
		stall_resistance = 0.0
	
	rpmforce += (rpm * (EngineDrag / clock_mult) ) * 1.0
	rpmforce -= (torque / clock_mult) * 1.0
	rpm -= rpmforce * RevSpeed
	
	engine_torque = torque


func apply_abs():
	if abs_delay > 0:
		brake_allowed -= abs.pump_rate
	else:
		brake_allowed += abs.pump_rate
	brake_allowed = clamp(brake_allowed, 0.0, 1.0)
	
	abs_delay -= 1


func apply_clutch_wear():
	pass # Future mechanic. Clutch wears over time, this calculates how much wear and applies its reduced effect.


func shift_up():
	pass


func shift_down():
	pass


func simulate_physical_steering():
	final_steer += steer_velocity
	
	if abs(final_steer) > 1.0:
		steer_velocity *= -0.5
	
	for i in [$fl,$fr]:
		steer_velocity += (i.directional_force.x * 0.00125) * i.Caster
		steer_velocity -= (i.stress * 0.0025) * (atan2(abs(i.wv), 1.0) * i.angle)
		
		steer_velocity += final_steer * (i.directional_force.z * 0.0005) * i.Caster
		
		if i.position.x > 0:
			steer_velocity += i.directional_force.z * 0.0001
		else:
			steer_velocity -= i.directional_force.z * 0.0001
		
		steer_velocity /= i.stress / (pow(i.slip_percpre, 2) * 100.0 + 1.0) + 1.0


func control_car():
	var left := Input.is_action_pressed("left")
	var right := Input.is_action_pressed("right")
	
	if ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.FULL:
		if gas and not gasrestricted and not gear == -1 or brake and gear == -1 or revmatch:
			gaspedal += ConfigManager.data.controls.on_throttle_rate / clock_mult
		else:
			gaspedal -= ConfigManager.data.controls.off_throttle_rate / clock_mult
		
		if brake and not gear == -1 or gas and gear == -1:
			brakepedal += ConfigManager.data.controls.on_brake_rate / clock_mult
		else:
			brakepedal -= ConfigManager.data.controls.off_brake_rate / clock_mult
	else:
		if ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.NONE:
			gasrestricted = false
			clutchin = false
			revmatch = false
		
		if gas and not gasrestricted or revmatch:
			gaspedal += ConfigManager.data.controls.on_throttle_rate / clock_mult
		else:
			gaspedal -= ConfigManager.data.controls.off_throttle_rate / clock_mult
		
		if brake:
			brakepedal += ConfigManager.data.controls.on_brake_rate / clock_mult
		else:
			brakepedal -= ConfigManager.data.controls.off_brake_rate / clock_mult
	
	if handbrake:
		handbrakepull += ConfigManager.data.controls.on_handbrake_rate / clock_mult
	else:
		handbrakepull -= ConfigManager.data.controls.off_handbrake_rate / clock_mult
	
	## Sideways movement.
	var siding := absf(velocity.x)
	
	if velocity.x > 0 and steer_target > 0 or velocity.x < 0 and steer_target < 0:
		siding = 0.0
	
	var going := velocity.z / (siding + 1.0)
	going = max(going, 0.0)
	
	var mouseposx = 0.0
	if get_viewport().size.x > 0.0:
		mouseposx = get_viewport().get_mouse_position().x / get_viewport().size.x
	
	if LooseSteering: return
	
	if ConfigManager.data.controls.mouse_steering:
		steer_target = (mouseposx - 0.5) * 2.0 * ConfigManager.data.controls.steering_sensitivity
		
		var s := absf(steer_target) * 1.0 + 0.5
		s = min(s, 1.0)
		
		steer_target *= s
	elif ConfigManager.data.controls.accelerometer_steering:
		steer_target = (Input.get_accelerometer().x / 10.0) * ConfigManager.data.controls.steering_sensitivity
		
		var s := absf(steer_target) * 1.0 + 0.5
		s = min(s, 1.0)
		
		steer_target *= s
	
	else:
		if right:
			if steer_target > 0:
				steer_target += ConfigManager.data.controls.keyboard_steer_speed
			else:
				steer_target += ConfigManager.data.controls.keyboard_compensate_speed
		elif left:
			if steer_target < 0:
				steer_target -= ConfigManager.data.controls.keyboard_steer_speed
			else:
				steer_target -= ConfigManager.data.controls.keyboard_compensate_speed
		else:
			if steer_target > ConfigManager.data.controls.keyboard_return_speed:
				steer_target -= ConfigManager.data.controls.keyboard_return_speed
			elif steer_target < -ConfigManager.data.controls.keyboard_return_speed:
				steer_target += ConfigManager.data.controls.keyboard_return_speed
			else:
				steer_target = 0.0
	
	if assistance_factor > 0.0:
		var maxsteer := 1.0 / (going * (ConfigManager.data.controls.steer_amount_decay / assistance_factor) + 1.0)
		
		var assist_commence := linear_velocity.length() / 10.0
		assist_commence = min(assist_commence, 1.0)
		
		final_steer = (steer_target * maxsteer) - (velocity.normalized().x * assist_commence) * (ConfigManager.data.controls.steering_assistance * assistance_factor) + rvelocity.y * (ConfigManager.data.controls.steering_assistance_angular * assistance_factor)
	else:
		final_steer = steer_target


func simulate_manual():
	if clutch and not clutchin:
		clutchpedalreal -= ConfigManager.data.controls.off_clutch_rate / clock_mult
	else:
		clutchpedalreal += ConfigManager.data.controls.on_clutch_rate / clock_mult
	
	clutchpedal = 1.0 - clutchpedalreal
	
	if gear > 0:
		ratio = GearRatios[gear-1] * final_drive * ratio_multi
	elif gear == -1:
		ratio = reverse_ratio * final_drive * ratio_multi
	
	if ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.NONE:
		if input_upshift:
			input_upshift = false
			if gear < len(GearRatios):
				if gearstress < GearGap:
					actualgear += 1
		if input_downshift:
			input_downshift = false
			if gear > -1 and gearstress < GearGap:
				actualgear -= 1
	elif ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.WEAK:
		if rpm < shift_assist.clutch_out_rpm:
			var irga_ca = (shift_assist.clutch_out_rpm - rpm) / (shift_assist.clutch_out_rpm - IdleRPM)
			clutchpedalreal = pow(irga_ca, 2)
		elif not gasrestricted and not revmatch:
			clutchin = false
		if input_upshift:
			input_upshift = false
			if gear < len(GearRatios):
				if rpm < shift_assist.clutch_out_rpm:
					actualgear += 1
				else:
					if actualgear < 1:
						actualgear += 1
						if rpm > shift_assist.clutch_out_rpm:
							clutchin = false
					else:
						if shift_assist_delay > 0:
							actualgear += 1
						shift_assist_delay = int(shift_assist.shift_delay / 2.0)
						sassiststep = -4
						
						clutchin = true
						gasrestricted = true
		elif input_downshift:
			input_downshift = false
			if gear > -1:
				if rpm < shift_assist.clutch_out_rpm:
					actualgear -= 1
				else:
					if actualgear == 0 or actualgear == 1:
						actualgear -= 1
						clutchin = false
					else:
						if shift_assist_delay > 0:
							actualgear -= 1
						shift_assist_delay = int(shift_assist.shift_delay / 2.0)
						sassiststep = -2
						
						clutchin = true
						revmatch = true
						gasrestricted = false
	elif ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.FULL:
		var assistshiftspeed = (shift_assist.upshift_rpm / ratio) * drivewheels_size
		var assistdownshiftspeed = (shift_assist.downshift_rpm / abs((GearRatios[gear-2] * final_drive) * ratio_multi)) * drivewheels_size
		if gear == 0:
			if gas:
				shift_assist_delay -= 1
				if shift_assist_delay < 0:
					actualgear = 1
			elif brake:
				shift_assist_delay -= 1
				if shift_assist_delay < 0:
					actualgear = -1
			else:
				shift_assist_delay = 60
		elif linear_velocity.length()<5:
			if not gas and gear == 1 or not brake and gear == -1:
				shift_assist_delay = 60
				actualgear = 0
		if sassiststep == 0:
			if rpm<shift_assist.clutch_out_rpm:
				var irga_ca = (shift_assist.clutch_out_rpm - rpm)/(shift_assist.clutch_out_rpm - IdleRPM)
				clutchpedalreal = pow(irga_ca, 2)
			else:
				clutchin = false
			if not gear == -1:
				if gear < len(GearRatios) and linear_velocity.length() > assistshiftspeed:
					shift_assist_delay = int(shift_assist.shift_delay / 2.0)
					sassiststep = -4
					
					clutchin = true
					gasrestricted = true
				if gear>1 and linear_velocity.length()<assistdownshiftspeed:
					shift_assist_delay = int(shift_assist.shift_delay / 2.0)
					sassiststep = -2
					
					clutchin = true
					gasrestricted = false
					revmatch = true
	
	if sassiststep == -4 and shift_assist_delay < 0:
		shift_assist_delay = int(shift_assist.shift_delay / 2.0)
		if gear<len(GearRatios):
			actualgear += 1
		sassiststep = -3
	elif sassiststep == -3 and shift_assist_delay < 0:
		if rpm > shift_assist.clutch_out_rpm:
			clutchin = false
		if shift_assist_delay < -shift_assist.post_shift_delay:
			sassiststep = 0
			gasrestricted = false
	elif sassiststep == -2 and shift_assist_delay < 0:
		sassiststep = 0
		if gear > -1:
			actualgear -= 1
		if rpm > shift_assist.clutch_out_rpm:
			clutchin = false
		gasrestricted = false
		revmatch = false
	
	gear = actualgear


func simulate_automatic_gearbox():
	clutchpedal = (rpm - auto_gearbox.engagement_min_rpm * (gaspedal * auto_gearbox.throttle_threshold + (1.0 - auto_gearbox.throttle_threshold) ) ) / auto_gearbox.engagement_max_rpm
	
	if not ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.FULL:
		if input_upshift:
			input_upshift = false
			if gear < 1:
				actualgear += 1
		if input_downshift:
			input_downshift = false
			if gear > -1:
				actualgear -= 1
	else:
		if gear == 0:
			if gas:
				shift_assist_delay -= 1
				if shift_assist_delay < 0:
					actualgear = 1
			elif brake:
				shift_assist_delay -= 1
				if shift_assist_delay < 0:
					actualgear = -1
			else:
				shift_assist_delay = 60
		elif linear_velocity.length() < 5:
			if not gas and gear == 1 or not brake and gear == -1:
				shift_assist_delay = 60
				actualgear = 0
	
	if actualgear == -1:
		ratio = reverse_ratio * final_drive * ratio_multi
	else:
		ratio = GearRatios[gear-1] * final_drive * ratio_multi
	if actualgear>0:
		var lastratio = GearRatios[gear-2] * final_drive * ratio_multi
		input_upshift = false
		input_downshift = false
		for i in c_pws:
			if (i.wv / drivewheels_size) > (auto_gearbox.upshift_rpm * (gaspedal * auto_gearbox.throttle_threshold + (1.0 - auto_gearbox.throttle_threshold))) / ratio:
				input_upshift = true
			elif (i.wv / drivewheels_size) < ((auto_gearbox.upshift_rpm - auto_gearbox.downshift_threshold) * (gaspedal * auto_gearbox.throttle_threshold + (1.0 - auto_gearbox.throttle_threshold))) /lastratio:
				input_downshift = true
		if input_upshift:
			gear += 1
		elif input_downshift:
			gear -= 1
		
		gear = clamp(gear, 1, len(GearRatios))
	else:
		gear = actualgear


func simulate_cvt():
	clutchpedal = (rpm - auto_gearbox.engagement_min_rpm * (gaspedal * auto_gearbox.throttle_threshold + (1.0 - auto_gearbox.throttle_threshold) ) ) / auto_gearbox.engagement_max_rpm
	
	if not ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.FULL:
		if input_upshift:
			input_upshift = false
			if gear < 1:
				actualgear += 1
		if input_downshift:
			input_downshift = false
			if gear > -1:
				actualgear -= 1
	else:
		if gear == 0:
			if gas:
				shift_assist_delay -= 1
				if shift_assist_delay<0:
					actualgear = 1
			elif brake:
				shift_assist_delay -= 1
				if shift_assist_delay<0:
					actualgear = -1
			else:
				shift_assist_delay = 60
		elif linear_velocity.length() < 5:
			if not gas and gear == 1 or not brake and gear == -1:
				shift_assist_delay = 60
				actualgear = 0
	
	gear = actualgear
	var wv := 0.0
	
	for i in c_pws:
		wv += i.wv / len(c_pws)
	
	cvtaccel -= (cvtaccel - (gaspedal * cvt.efficiency_range +(1.0-cvt.efficiency_range)))*cvt.ratio_step_rate
	
	var a := cvt.lock_timing / ( (absf(wv) / 10.0) * cvtaccel + 1.0)
	
	a = max(a, cvt.stability_damping)
	
	ratio = (cvt.rpm_offset * 10000000.0) / (abs(wv) * (rpm * a) + 1.0)
	ratio = min(ratio, cvt.standstill_torque)


func simulate_semi_auto_gearbox():
	clutchpedal = (rpm - auto_gearbox.engagement_min_rpm * (gaspedal * auto_gearbox.throttle_threshold + (1.0 - auto_gearbox.throttle_threshold) ) ) / auto_gearbox.engagement_max_rpm
	
	if gear > 0:
		ratio = GearRatios[gear-1] * final_drive * ratio_multi
	elif gear == -1:
		ratio = reverse_ratio * final_drive * ratio_multi
	
	if ConfigManager.data.controls.shift_assist_level < ControlsConfig.ShiftAssistLevel.FULL:
		if input_upshift:
			input_upshift = false
			if gear < len(GearRatios):
				actualgear += 1
		if input_downshift:
			input_downshift = false
			if gear > -1:
				actualgear -= 1
	else:
		var assistshiftspeed := (shift_assist.upshift_rpm / ratio) * drivewheels_size
		var assistdownshiftspeed = (shift_assist.downshift_rpm / abs((GearRatios[gear-2] * final_drive) * ratio_multi)) * drivewheels_size
		if gear == 0:
			if gas:
				shift_assist_delay -= 1
				if shift_assist_delay<0:
					actualgear = 1
			elif brake:
				shift_assist_delay -= 1
				if shift_assist_delay<0:
					actualgear = -1
			else:
				shift_assist_delay = 60
		elif linear_velocity.length() < 5:
			if not gas and gear == 1 or not brake and gear == -1:
				shift_assist_delay = 60
				actualgear = 0
		if sassiststep == 0:
			if not gear == -1:
				if gear < len(GearRatios) and linear_velocity.length() > assistshiftspeed:
					actualgear += 1
				if gear > 1 and linear_velocity.length() < assistdownshiftspeed:
					actualgear -= 1
	
	gear = actualgear


func bullet_fix():
	var offset = $DRAG_CENTRE.position
	AckermannPoint -= offset.z
	
	for i in get_children():
		i.position -= offset


func controls():
	# IMPORTANT: Why if else in controls and in transmission?
	if ConfigManager.data.controls.mouse_steering:
		gas = Input.is_action_pressed("gas_mouse")
		brake = Input.is_action_pressed("brake_mouse")
		input_upshift = Input.is_action_just_pressed("shiftup_mouse")
		input_downshift = Input.is_action_just_pressed("shiftdown_mouse")
		handbrake = Input.is_action_pressed("handbrake_mouse")
	else:
		gas = Input.is_action_pressed("gas")
		brake = Input.is_action_pressed("brake")
		input_upshift = Input.is_action_just_pressed("shiftup")
		input_downshift = Input.is_action_just_pressed("shiftdown")
		handbrake = Input.is_action_pressed("handbrake")
	
	steer_velocity += 0.01 * Input.get_axis("left", "right")
	
	if LooseSteering:
		simulate_physical_steering()
	
	if Controlled:
		control_car()


func transmission():
	if Controlled:
		clutch = Input.is_action_pressed("clutch") and not ConfigManager.data.controls.mouse_steering or Input.is_action_pressed("clutch_mouse") and ConfigManager.data.controls.mouse_steering
		if not ConfigManager.data.controls.shift_assist_level == ControlsConfig.ShiftAssistLevel.NONE:
			clutch = Input.is_action_pressed("handbrake") and not ConfigManager.data.controls.mouse_steering or Input.is_action_pressed("handbrake_mouse") and ConfigManager.data.controls.mouse_steering
		clutch = !clutch
	
	if transmission_type == TransmissionType.FULLY_MANUAL:
		simulate_manual()
	elif transmission_type == TransmissionType.AUTOMATIC:
		simulate_automatic_gearbox()
	elif transmission_type == TransmissionType.CONTINUOUSLY_VARIABLE:
		simulate_cvt()
	elif transmission_type == TransmissionType.SEMI_AUTO:
		simulate_semi_auto_gearbox()


func drivetrain():
	rpmcsm -= (rpmcs - resistance)
	rpmcs += rpmcsm*ClutchElasticity
	rpmcs -= rpmcs * (1.0 - clutchpedal)
	wob = ClutchWobble * clutchpedal
	wob *= ratio * WobbleRate
	rpmcs -= (rpmcs - resistance) * (1.0 / (wob + 1.0) )
	
	var rpm_change := ((rpmcs * 1.0) / clock_mult) * (RevSpeed / Constants.REVSPEED_TUNE)
	if gear < 0:
		rpm -= rpm_change
	else:
		rpm += rpm_change
	
	gearstress = (abs(resistance) * StressFactor) * clutchpedal
	var stabled := ratio * 0.9 + 0.1
	ds_weight = DSWeight / stabled
	
	whinepitch = abs(rpm / ratio) * 1.5
	
	if resistance > 0.0:
		locked = abs(resistance / ds_weight) * (CoastLocking / 100.0) + Preload
	else:
		locked = abs(resistance / ds_weight) * (Locking / 100.0) + Preload
	
	locked = clamp(locked, 0.0, 1.0)
	
	
	if wv_difference > 0.0:
		c_locked = abs(wv_difference) * (Centre_CoastLocking / 10.0) + Centre_Preload
	else:
		c_locked = abs(wv_difference) * (Centre_Locking / 10.0) + Centre_Preload
	if len(c_pws) < 4:
		c_locked = 0.0
	c_locked = clamp(c_locked, 0.0, 1.0)
	
	var maxd = VitaVehicleSimulation.fastest_wheel(c_pws)
	#var mind = VitaVehicleSimulation.slowest_wheel(c_pws)
	var what := 0.0
	
	var floatreduction := ClutchFloatReduction
	
	if dsweightrun > 0.0:
		floatreduction = ClutchFloatReduction / dsweightrun
	else:
		floatreduction = 0.0
	
	var stabling := -(GearRatioRatioThreshold - ratio * drivewheels_size) * ThresholdStable
	stabling = max(stabling, 0.0)
	
	currentstable = ClutchStable + stabling
	currentstable *= (RevSpeed / Constants.REVSPEED_TUNE)
	
	if dsweightrun > 0.0:
		what = (rpm - (((rpmforce * floatreduction) * currentstable) / (ds_weight / dsweightrun)))
	else:
		what = rpm
	
	if gear < 0.0:
		dist = maxd.wv + what / ratio
	else:
		dist = maxd.wv - what / ratio
	
	dist *= pow(clutchpedal, 2)
	
	if gear == 0:
		dist = 0.0
	
	wv_difference = 0.0
	drivewheels_size = 0.0
	for i in c_pws:
		drivewheels_size += i.w_size / len(c_pws)
		i.c_p = i.W_PowerBias
		wv_difference += ((i.wv - what / ratio) / (len(c_pws))) * pow(clutchpedal, 2)
		if gear < 0:
			i.dist = dist * (1 - c_locked) + (i.wv + what / ratio) * c_locked
		elif gear > 0:
			i.dist = dist * (1 - c_locked) + (i.wv - what / ratio) * c_locked
		else:
			i.dist = 0.0
	
	resistance = 0.0
	dsweightrun = dsweight
	dsweight = 0.0
	tcsweight = 0.0
	stress = 0.0


func simulate_fuel():
	if !fuel: return
	
	# New BSFC-based API: pass the whole car so the model can read throttle,
	# AFR target, boost, gear, clutch state etc. The fuel resource handles
	# DFCO/ignition internally. Older Fuel resources without the new fields
	# still work because their idle_consumption export is preserved.
	var fuel_consumption: float = fuel.get_consumption(self)
	
	current_fuel -= fuel_consumption * get_physics_process_delta_time()
	
	if current_fuel <= 0.0:
		current_fuel = 0.0
		stop_engine()


func aero():
	var drag := DragCoefficient
	var df := Downforce
	
	var veloc := global_transform.basis.orthonormalized().transposed() * (linear_velocity)
	
	#var torq := global_transform.basis.orthonormalized().transposed() * (Vector3(1, 0, 0))
	
	apply_torque_impulse(global_transform.basis.orthonormalized() * ( Vector3(((-veloc.length()*0.3)*LiftAngle), 0, 0)  ) )
	
	# TODO: Extract magic value.
	var vx := veloc.x * 0.15
	var vy := veloc.z * 0.15
	var vz := veloc.y * 0.15
	var vl := veloc.length() * 0.15
	
	var forc := global_transform.basis.orthonormalized() * Vector3(-vx * drag, -vl * df -vz * drag, -vy * drag)
	
	if has_node("DRAG_CENTRE"):
		apply_impulse(forc, global_transform.basis.orthonormalized() * ($DRAG_CENTRE.position))
	else:
		apply_central_impulse(forc)


func draw_debug():
	# BUG: Why do this each frame? Initialize with events no?
		front_wheels = []
		rear_wheels = []
		for i in get_children():
			if "TyreSettings" in i:
				if i.position.z > 0: # IMPORTANT: So weird to check by distance. What if an origin is shifted?
					front_wheels.append(i)
				else:
					rear_wheels.append(i)
		
		front_load = 0.0
		total = 0.0
		
		for f in front_wheels:
			front_load += f.directional_force.y
			total += f.directional_force.y
		for r in rear_wheels:
			front_load -= r.directional_force.y
			total += r.directional_force.y
		
		if total > 0:
			weight_dist[0] = remap(front_load / total, -1.0, 1.0, 0.0, 1.0)
			weight_dist[1] = 1.0 - weight_dist[0]


func start_engine():
	# TODO: This ignites the engine back up, make it more... natural. WARNING: Don't assume i start from 0.
	rpm = max(rpm, IdleRPM)
	is_ignition_on = true


func stop_engine():
	is_ignition_on = false


func is_above_idle_rpm():
	return rpm > IdleRPM


## Asks [code]CarManager[/code] (if present) to hand control to this car.
## No-op when the autoload isn't configured.
func make_active() -> void:
	var cm := _find_car_manager()
	if cm != null:
		cm.call("set_active", self)
	else:
		Controlled = true
